// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsaWvigCHqSPPBIHabwZiCWgCmte2O6sY',
    appId: '1:930184663597:web:162f3af2423081edfb1ea4',
    messagingSenderId: '930184663597',
    projectId: 'snack-dating-2981c',
    authDomain: 'snack-dating-2981c.firebaseapp.com',
    databaseURL: 'https://snack-dating-2981c.firebaseio.com',
    storageBucket: 'snack-dating-2981c.appspot.com',
    measurementId: 'G-Q6DJ9JJLLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfGrqMOCR_ooDM58NOGOgbA8jyz1-_FE4',
    appId: '1:930184663597:android:2b1616264c2506e2fb1ea4',
    messagingSenderId: '930184663597',
    projectId: 'snack-dating-2981c',
    databaseURL: 'https://snack-dating-2981c.firebaseio.com',
    storageBucket: 'snack-dating-2981c.appspot.com',
  );
}
